FROM openjdk:latest
LABEL authors="kamiliskhakov"
LABEL version="1.0"
LABEL description="he-he"
LABEL maintainer="kamiliskhakov"
COPY ./out/production/laba5.3/ /tmp
WORKDIR /tmp
ENTRYPOINT ["java", "Main"]